### PR TITLE
RK-9007 - expose ROOKOUT_DOP_NO_SSL_VERIFY to chart settings

### PR DESCRIPTION
**Pull request by adilrookout**

### CODE REVIEW

**Comment by lirook** [comment]
What's the difference between ROOKOUT_SKIP_SSL_VERIFY and ROOKOUT_DOP_NO_SSL_VERIFY? Do we want both?

**Comment by adilrookout** [comment]
`ROOKOUT_SKIP_SSL_VERIFY` used by the controller when it tries to send request to other targets like slack or generic webhooks

`ROOKOUT_DOP_NO_SSL_VERIFY` is only for the communication between the controller and the DOP

We might consider to combine them into single variable

**Comment by Gilwe** [comment]
I see no reason to combine them, maybe that edge case of having dop with ssl and controller with skip-ssl (or vice-versa) in the future.

**Comment by Gilwe** [comment]
im confused with this PR, you want to add a DOP-SKIP-SSL env var but to the controller chart? why not to the dop chart?

**Comment by adilrookout** [comment]
@Gilwe this env var used by the on-prem controller here :

image

**Comment by ElDuderinos** [comment]
@adilrookout  - Did any customer request this?
Anyway, let's finish up with this PR?

**Comment by adilrookout** [comment]
@lirook asked for it

**Comment by ElDuderinos** [comment]
> @lirook asked for it

I guess he is sort of a customer :)

**Review by Gilwe — APPROVED** [review]

**Pull request merged**
